spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 1MB #파일 하나의 최대 사이즈

#swagger
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100